target:
	#SimpleThread
	javac com/wade/thread/RandomThread.java
	javac SimpleThreadDemo.java
	#SimpleThreadServer
	javac com/wade/thread/ReqHandler.java
	javac SimpleThreadServer.java
	#Fixed ThreadPoolServer
	javac com/wade/thread/HandleRequestRunnable.java
	javac ThreadPoolServer.java
	#Bounded Fixed ThreadPool
	javac ThreadPoolQueue.java

run:
	java SimpleThreadDemo
	#java SimpleThreadServer
	#java ThreadPoolServer
	#java ThreadPoolQueue
	
